<font size = 5>

How often does a state’s presidential party vote match the senator, house rep and governor party?

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
#Import datasets
df_state = pd.read_csv("4-US_Election_2020/president_county_candidate.csv")
df_senator = pd.read_csv("4-US_Election_2020/senate_county_candidate.csv")
df_house = pd.read_csv("4-US_Election_2020/house_candidate.csv")
df_governor = pd.read_csv("4-US_Election_2020/governors_county_candidate.csv")

print(f"Rows,Columns of state: {df_state.shape}")
print(f"Rows,Columns of senator: {df_senator.shape}")
print(f"Rows,Columns of house: {df_house.shape}")
print(f"Rows,Columns of governor: {df_governor.shape}")

display(df_state.head())

Rows,Columns of state: (32177, 6)
Rows,Columns of senator: (14125, 5)
Rows,Columns of house: (1215, 5)
Rows,Columns of governor: (5145, 6)

      state             county      candidate party  total_votes    won
0  Delaware        Kent County      Joe Biden   DEM        44552   True
1  Delaware        Kent County   Donald Trump   REP        41009  False
2  Delaware        Kent County   Jo Jorgensen   LIB         1044  False
3  Delaware        Kent County  Howie Hawkins   GRN          420  False
4  Delaware  New Castle County      Joe Biden   DEM       195034   True

In [3]:
states = []
prop_dem = []
prop_rep = []
prop_ind = []
winner = []


for group in df_state.groupby("state"): #groupby groups the data by state. group includes the state name and then all its associated data
    state_name = group[0] #grabs the state name of a group
    state_data = group[1] #grabs the data that corresponds to the state name
    states.append(state_name)

    total = 0 #total number of votes
    dem = 0 #number of democrats
    rep = 0 #number of republicans
    ind = 0 #number of independents
    prop_dems = 0 #proportion of democratic votes
    prop_reps = 0 #proportion of republican votes
    prop_inds = 0 #proportion of independent votes
    win = "no one" #party of the president the state voted for

    for votes, party in zip(state_data["total_votes"], state_data["party"]): #loops through "total_votes" and "party" for each state
        total = total + votes #calculates total votes for each state
        if party == "DEM": #these statements count the number of democrat, republican and independent votes respectively
            dem = dem + votes
        elif party == "REP":
            rep = rep + votes
        else:
            ind = ind + votes
    
    prop_dems = dem/total #proportion of democratic votes
    prop_reps = rep/total #proportion of republican votes
    prop_inds = ind/total #proportion of independent votes

    prop_dem.append(prop_dems)
    prop_rep.append(prop_reps)
    prop_ind.append(prop_inds)   

    if prop_dems > prop_reps and prop_dems > prop_inds: #these statements determine which party won
        win = "DEM"
    elif prop_reps > prop_dems and prop_reps > prop_inds:
        win = "REP"
    else:
        win = "IND"

    winner.append(win)

#creates a new dataframe with the proportions of votes for each party and the winner for each state
state_proportions = pd.DataFrame({"State": states, "Proportion_Democrat": prop_dem, "Proportion_Republican":prop_rep, "Proportion_Independent": prop_ind, "Presidential_Party": winner})

display(state_proportions)

,State,Proportion_Democrat,Proportion_Republican,Proportion_Independent,Presidential_Party
0,Alabama,0.365707,0.620310,0.013984,REP
1,Alaska,0.391993,0.485228,0.122779,REP
2,Arizona,0.493647,0.490560,0.015793,DEM
3,Arkansas,0.347751,0.623957,0.028292,REP
4,California,0.634992,0.343278,0.021730,DEM
5,Colorado,0.554000,0.418983,0.027017,DEM
6,Connecticut,0.592387,0.392095,0.015518,DEM
7,Delaware,0.587822,0.398014,0.014164,DEM
8,District of Columbia,0.921497,0.053973,0.024530,DEM
9,Florida,0.478615,0.512198,0.009187,REP
10,Georgia,0.494953,0.492596,0.012451,DEM
11,Hawaii,0.637336,0.342689,0.019975,DEM
12,Idaho,0.330629,0.638308,0.031063,REP
13,Illinois,0.589447,0.391369,0.019184,DEM
14,Indiana,0.409632,0.570306,0.020062,REP
15,Iowa,0.448917,0.530893,0.020190,REP
16,Kansas,0.413962,0.561736,0.024303,REP
17,Kentucky,0.361515,0.620866,0.017619,REP
18,Louisiana,0.398515,0.584609,0.016877,REP
19,Maine,0.529006,0.442278,0.028717,DEM
20,Maryland,0.653607,0.321503,0.024890,DEM
21,Massachusetts,0.656001,0.321419,0.022580,DEM
22,Michigan,0.506208,0.478373,0.015419,DEM
23,Minnesota,0.523951,0.452849,0.023200,DEM
24,Mississippi,0.410132,0.575406,0.014462,REP
25,Missouri,0.414088,0.567997,0.017916,REP
26,Montana,0.404104,0.567234,0.028662,REP
27,Nebraska,0.391668,0.582244,0.026088,REP
28,Nevada,0.500568,0.476662,0.022770,DEM
29,New Hampshire,0.528226,0.454550,0.017223,DEM
30,New Jersey,0.571473,0.412616,0.015912,DEM
31,New Mexico,0.542893,0.434967,0.022140,DEM
32,New York,0.608809,0.377339,0.013851,DEM
33,North Carolina,0.485862,0.499343,0.014794,REP
34,North Dakota,0.317568,0.651140,0.031292,REP
35,Ohio,0.452393,0.532713,0.014894,REP
36,Oklahoma,0.322862,0.653733,0.023406,REP
37,Oregon,0.564533,0.403672,0.031794,DEM
38,Pennsylvania,0.499609,0.487818,0.012573,DEM
39,Rhode Island,0.592990,0.386994,0.020016,DEM
40,South Carolina,0.434301,0.551103,0.014596,REP
41,South Dakota,0.356053,0.617694,0.026254,REP
42,Tennessee,0.374497,0.606622,0.018881,REP
43,Texas,0.464673,0.520445,0.014882,REP
44,Utah,0.376460,0.581298,0.042241,REP
45,Vermont,0.660864,0.306738,0.032398,DEM
46,Virginia,0.541095,0.439955,0.018950,DEM
47,Washington,0.579703,0.387670,0.032627,DEM
48,West Virginia,0.296965,0.686316,0.016719,REP
49,Wisconsin,0.494540,0.488290,0.017170,DEM
50,Wyoming,0.265536,0.699362,0.035102,REP

In [4]:
states = []
prop_dem = []
prop_rep = []
prop_ind = []
winner = []


for group in df_senator.groupby("state"): #groupby groups the data by state. group includes the state name and then all its associated data
    state_name = group[0] #grabs the state name of a group
    state_data = group[1] #grabs the data that corresponds to the state name
    states.append(state_name)

    total = 0 #total number of votes
    dem = 0 #number of democrats
    rep = 0 #number of republicans
    ind = 0 #number of independents
    prop_dems = 0 #proportion of democratic votes
    prop_reps = 0 #proportion of republican votes
    prop_inds = 0 #proportion of independent votes
    win = "no one" #party of the president the state voted for

    for votes, party in zip(state_data["total_votes"], state_data["party"]): #loops through "total_votes" and "party" for each state
        total = total + votes #calculates total votes for each state
        if party == "DEM": #these statements count the number of democrat, republican and independent votes respectively
            dem = dem + votes
        elif party == "REP":
            rep = rep + votes
        else:
            ind = ind + votes
    
    prop_dems = dem/total #proportion of democratic votes
    prop_reps = rep/total #proportion of republican votes
    prop_inds = ind/total #proportion of independent votes

    prop_dem.append(prop_dems)
    prop_rep.append(prop_reps)
    prop_ind.append(prop_inds)   

    if prop_dems > prop_reps and prop_dems > prop_inds: #these statements determine which party won
        win = "DEM"
    elif prop_reps > prop_dems and prop_reps > prop_inds:
        win = "REP"
    else:
        win = "IND"

    winner.append(win)

#creates a new dataframe with the proportions of votes for each party and the winner for each state
senator_proportions = pd.DataFrame({"State": states, "Proportion_Democrat": prop_dem, "Proportion_Republican":prop_rep, "Proportion_Independent": prop_ind, "Senator_Party": winner})

display(senator_proportions)

,State,Proportion_Democrat,Proportion_Republican,Proportion_Independent,Senator_Party
0,Alabama,0.745786,0.249344,0.004869,DEM
1,Alaska,0.590108,0.294475,0.115417,DEM
2,Arizona,0.173511,0.825695,0.000795,REP
3,Arkansas,0.000000,0.228876,0.771124,IND
4,Colorado,0.350723,0.589283,0.059994,REP
5,Delaware,0.298814,0.631578,0.069608,REP
6,Georgia,0.405144,0.544882,0.049975,REP
7,Idaho,0.834971,0.052484,0.112545,DEM
8,Illinois,0.210579,0.625000,0.164421,REP
9,Iowa,0.513389,0.414488,0.072122,DEM
10,Kansas,0.456977,0.422607,0.120416,DEM
11,Kentucky,0.615055,0.276022,0.108923,DEM
12,Louisiana,0.822176,0.085683,0.092141,DEM
13,Maine,0.546745,0.294795,0.158460,DEM
14,Massachusetts,0.077258,0.898904,0.023838,REP
15,Michigan,0.529049,0.425138,0.045813,DEM
16,Minnesota,0.361925,0.456819,0.181256,REP
17,Mississippi,0.666199,0.284435,0.049366,DEM
18,Montana,0.597679,0.402321,0.000000,DEM
19,Nebraska,0.573958,0.000000,0.426042,DEM
20,New Hampshire,0.242595,0.701714,0.055691,REP
21,New Jersey,0.241354,0.709759,0.048887,REP
22,New Mexico,0.213179,0.719281,0.067540,REP
23,North Carolina,0.423432,0.466471,0.110097,REP
24,Oklahoma,0.883133,0.000000,0.116867,DEM
25,Oregon,0.292074,0.609676,0.098250,REP
26,Rhode Island,0.061050,0.938950,0.000000,REP
27,South Carolina,0.727278,0.239846,0.032876,DEM
28,South Dakota,0.980254,0.019746,0.000000,DEM
29,Tennessee,0.658772,0.258763,0.082465,DEM
30,Texas,0.465067,0.467064,0.067869,REP
31,Virginia,0.329312,0.670688,0.000000,REP
32,West Virginia,0.908603,0.000000,0.091397,DEM
33,Wyoming,0.922293,0.077707,0.000000,DEM

In [5]:
states = []
prop_dem = []
prop_rep = []
prop_ind = []
winner = []


for group in df_governor.groupby("state"): #groupby groups the data by state. group includes the state name and then all its associated data
    state_name = group[0] #grabs the state name of a group
    state_data = group[1] #grabs the data that corresponds to the state name
    states.append(state_name)

    total = 0 #total number of votes
    dem = 0 #number of democrats
    rep = 0 #number of republicans
    ind = 0 #number of independents
    prop_dems = 0 #proportion of democratic votes
    prop_reps = 0 #proportion of republican votes
    prop_inds = 0 #proportion of independent votes
    win = "no one" #party of the president the state voted for

    for votes, party in zip(state_data["votes"], state_data["party"]): #loops through "total_votes" and "party" for each state
        total = total + votes #calculates total votes for each state
        if party == "DEM": #these statements count the number of democrat, republican and independent votes respectively
            dem = dem + votes
        elif party == "REP":
            rep = rep + votes
        else:
            ind = ind + votes
    
    prop_dems = dem/total #proportion of democratic votes
    prop_reps = rep/total #proportion of republican votes
    prop_inds = ind/total #proportion of independent votes

    prop_dem.append(prop_dems)
    prop_rep.append(prop_reps)
    prop_ind.append(prop_inds)   

    if prop_dems > prop_reps and prop_dems > prop_inds: #these statements determine which party won
        win = "DEM"
    elif prop_reps > prop_dems and prop_reps > prop_inds:
        win = "REP"
    else:
        win = "IND"

    winner.append(win)

#creates a new dataframe with the proportions of votes for each party and the winner for each state
governor_proportions = pd.DataFrame({"State": states, "Governor_Party": winner})

display(governor_proportions)

             State Governor_Party
0         Delaware            DEM
1          Indiana            REP
2         Missouri            REP
3          Montana            REP
4    New Hampshire            REP
5   North Carolina            DEM
6     North Dakota            REP
7             Utah            REP
8          Vermont            REP
9       Washington            DEM
10   West Virginia            REP

In [6]:
#Data Cleaning House
states_list = [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California",
    "Colorado", "Connecticut", "Delaware", "Florida", "Georgia",
    "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa",
    "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland",
    "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri",
    "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey",
    "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio",
    "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
    "South Dakota", "Tennessee", "Texas", "Utah", "Vermont",
    "West Virginia", "Washington", "Virginia", "Wisconsin", "Wyoming"
]
States = []

for district in df_house["district"]:
    for index in range(len(states_list)):
        if states_list[index] in district:
            States.append(states_list[index])
            break
    else:
        States.append("None")
        

df_house["States"] = States

In [7]:
house_winners_agg = df_house.query("won == True")
display(house_winners_agg)

,district,candidate,party,total_votes,won,States
0,Delaware at large,Lisa Blunt Rochester,DEM,281382,True,Delaware
4,Florida’s 1st district,Matt Gaetz,REP,283352,True,Florida
7,Florida’s 2nd district,Neal Dunn,REP,305337,True,Florida
9,Florida’s 3rd district,Kat Cammack,REP,223075,True,Florida
11,Florida’s 4th district,John Rutherford,REP,308497,True,Florida
...,...,...,...,...,...,...
1203,Connecticut’s 5th district,Jahana Hayes,DEM,192484,True,Connecticut
1206,United States’s 0th district,The Democratic candidate,DEM,77138263,True,None
1209,California’s 21st district,David Valadao,REP,85928,True,California
1211,California’s 25th district,Mike Garcia,REP,169638,True,California
1213,California’s 39th district,Young Kim,REP,173946,True,California

In [8]:
states = []
prop_dem = []
prop_rep = []
prop_ind = []
winner = []


for group in house_winners_agg.groupby("States"): #groupby groups the data by state. group includes the state name and then all its associated data
    state_name = group[0] #grabs the state name of a group
    state_data = group[1] #grabs the data that corresponds to the state name
    states.append(state_name)

    total = 0 #total number of votes
    dem = 0 #number of democrats
    rep = 0 #number of republicans
    ind = 0 #number of independents
    prop_dems = 0 #proportion of democratic votes
    prop_reps = 0 #proportion of republican votes
    prop_inds = 0 #proportion of independent votes
    win = "no one" #party of the president the state voted for

    for party in state_data["party"]: #loops through "total_votes" and "party" for each state
        total = total + 1 #calculates total votes for each state
        if party == "DEM": #these statements count the number of democrat, republican and independent votes respectively
            dem = dem + 1
        elif party == "REP":
            rep = rep + 1
        else:
            ind = ind + 1
    
    prop_dems = dem/total #proportion of democratic votes
    prop_reps = rep/total #proportion of republican votes
    prop_inds = ind/total #proportion of independent votes

    prop_dem.append(prop_dems)
    prop_rep.append(prop_reps)
    prop_ind.append(prop_inds)   

    if prop_dems > prop_reps and prop_dems > prop_inds: #these statements determine which party won
        win = "DEM"
    elif prop_reps > prop_dems and prop_reps > prop_inds:
        win = "REP"
    else:
        win = "IND"

    winner.append(win)

#creates a new dataframe with the proportions of votes for each party and the winner for each state
house_proportions = pd.DataFrame({"State": states, "Proportion_Democrat": prop_dem, "Proportion_Republican":prop_rep, "Proportion_Independent": prop_ind, "House_Majority": winner})

display(house_proportions)

,State,Proportion_Democrat,Proportion_Republican,Proportion_Independent,House_Majority
0,Alabama,0.142857,0.857143,0.0,REP
1,Alaska,0.000000,1.000000,0.0,REP
2,Arizona,0.555556,0.444444,0.0,DEM
3,Arkansas,0.000000,1.000000,0.0,REP
4,California,0.792453,0.207547,0.0,DEM
5,Colorado,0.571429,0.428571,0.0,DEM
6,Connecticut,1.000000,0.000000,0.0,DEM
7,Delaware,1.000000,0.000000,0.0,DEM
8,Florida,0.407407,0.592593,0.0,REP
9,Georgia,0.428571,0.571429,0.0,REP
10,Hawaii,1.000000,0.000000,0.0,DEM
11,Idaho,0.000000,1.000000,0.0,REP
12,Illinois,0.722222,0.277778,0.0,DEM
13,Indiana,0.222222,0.777778,0.0,REP
14,Iowa,0.250000,0.750000,0.0,REP
15,Kansas,0.250000,0.750000,0.0,REP
16,Kentucky,0.166667,0.833333,0.0,REP
17,Louisiana,0.166667,0.833333,0.0,REP
18,Maine,1.000000,0.000000,0.0,DEM
19,Maryland,0.875000,0.125000,0.0,DEM
20,Massachusetts,1.000000,0.000000,0.0,DEM
21,Michigan,0.500000,0.500000,0.0,IND
22,Minnesota,0.500000,0.500000,0.0,IND
23,Mississippi,0.250000,0.750000,0.0,REP
24,Missouri,0.250000,0.750000,0.0,REP
25,Montana,0.000000,1.000000,0.0,REP
26,Nebraska,0.000000,1.000000,0.0,REP
27,Nevada,0.750000,0.250000,0.0,DEM
28,New Hampshire,1.000000,0.000000,0.0,DEM
29,New Jersey,0.833333,0.166667,0.0,DEM
30,New Mexico,0.666667,0.333333,0.0,DEM
31,New York,0.703704,0.296296,0.0,DEM
32,None,1.000000,0.000000,0.0,DEM
33,North Carolina,0.384615,0.615385,0.0,REP
34,North Dakota,0.000000,1.000000,0.0,REP
35,Ohio,0.250000,0.750000,0.0,REP
36,Oklahoma,0.000000,1.000000,0.0,REP
37,Oregon,0.800000,0.200000,0.0,DEM
38,Pennsylvania,0.500000,0.500000,0.0,IND
39,Rhode Island,1.000000,0.000000,0.0,DEM
40,South Carolina,0.142857,0.857143,0.0,REP
41,South Dakota,0.000000,1.000000,0.0,REP
42,Tennessee,0.222222,0.777778,0.0,REP
43,Texas,0.361111,0.638889,0.0,REP
44,Utah,0.000000,1.000000,0.0,REP
45,Vermont,1.000000,0.000000,0.0,DEM
46,Virginia,0.636364,0.363636,0.0,DEM
47,Washington,0.700000,0.300000,0.0,DEM
48,West Virginia,0.000000,1.000000,0.0,REP
49,Wisconsin,0.375000,0.625000,0.0,REP
50,Wyoming,0.000000,1.000000,0.0,REP

In [9]:
#merge everything
state_senator = pd.merge(left = state_proportions[["State","Presidential_Party"]], 
    right = senator_proportions[["State", "Senator_Party"]], 
    how = "left", on = "State")

state_senator_house = pd.merge(left = state_senator, 
    right = house_proportions[["State", "House_Majority"]], 
    how = "left", on = "State")

merged = pd.merge(left = state_senator_house, 
    right = governor_proportions[["State", "Governor_Party"]], 
    how = "left", on = "State")

display(merged)

,State,Presidential_Party,Senator_Party,House_Majority,Governor_Party
0,Alabama,REP,DEM,REP,NaN
1,Alaska,REP,DEM,REP,NaN
2,Arizona,DEM,REP,DEM,NaN
3,Arkansas,REP,IND,REP,NaN
4,California,DEM,NaN,DEM,NaN
5,Colorado,DEM,REP,DEM,NaN
6,Connecticut,DEM,NaN,DEM,NaN
7,Delaware,DEM,REP,DEM,DEM
8,District of Columbia,DEM,NaN,NaN,NaN
9,Florida,REP,NaN,REP,NaN
10,Georgia,DEM,REP,REP,NaN
11,Hawaii,DEM,NaN,DEM,NaN
12,Idaho,REP,DEM,REP,NaN
13,Illinois,DEM,REP,DEM,NaN
14,Indiana,REP,NaN,REP,REP
15,Iowa,REP,DEM,REP,NaN
16,Kansas,REP,DEM,REP,NaN
17,Kentucky,REP,DEM,REP,NaN
18,Louisiana,REP,DEM,REP,NaN
19,Maine,DEM,DEM,DEM,NaN
20,Maryland,DEM,NaN,DEM,NaN
21,Massachusetts,DEM,REP,DEM,NaN
22,Michigan,DEM,DEM,IND,NaN
23,Minnesota,DEM,REP,IND,NaN
24,Mississippi,REP,DEM,REP,NaN
25,Missouri,REP,NaN,REP,REP
26,Montana,REP,DEM,REP,REP
27,Nebraska,REP,DEM,REP,NaN
28,Nevada,DEM,NaN,DEM,NaN
29,New Hampshire,DEM,REP,DEM,REP
30,New Jersey,DEM,REP,DEM,NaN
31,New Mexico,DEM,REP,DEM,NaN
32,New York,DEM,NaN,DEM,NaN
33,North Carolina,REP,REP,REP,DEM
34,North Dakota,REP,NaN,REP,REP
35,Ohio,REP,NaN,REP,NaN
36,Oklahoma,REP,DEM,REP,NaN
37,Oregon,DEM,REP,DEM,NaN
38,Pennsylvania,DEM,NaN,IND,NaN
39,Rhode Island,DEM,REP,DEM,NaN
40,South Carolina,REP,DEM,REP,NaN
41,South Dakota,REP,DEM,REP,NaN
42,Tennessee,REP,DEM,REP,NaN
43,Texas,REP,REP,REP,NaN
44,Utah,REP,NaN,REP,REP
45,Vermont,DEM,NaN,DEM,REP
46,Virginia,DEM,REP,DEM,NaN
47,Washington,DEM,NaN,DEM,DEM
48,West Virginia,REP,DEM,REP,REP
49,Wisconsin,DEM,NaN,REP,NaN
50,Wyoming,REP,DEM,REP,NaN

In [10]:
num_statesen = len(merged.query("Presidential_Party == Senator_Party"))
print(len(merged["Senator_Party"]))

51